stages:
- build
- deploy

workflow:
  rules:
  - if: '$CI_COMMIT_MESSAGE =~ /\[production\]/ || $CI_COMMIT_MESSAGE =~ /\[dev\]/'
  - when: never

variables:
  IMAGE_NAME: "registry.part-pack.ir/part-pack/backend"
  IMAGE_TAG: "production"
  INFRA_PROJECT_ID: "8"
  INFRA_REF: "main"
  DEPLOY_SERVICE: "backend"
  GITLAB_API_URL: "https://gitlab.part-pack.ir/api/v4"
  IMAGE_TAG_DEV: "development"

build_dev:
  stage: build
  tags: 
  - part-pack-backend-dev
  rules:
  - if: '$CI_COMMIT_MESSAGE =~ /\[dev\]/'
  script:
  - docker build -t "$IMAGE_NAME:$IMAGE_TAG_DEV" .
  - docker images | grep part-pack/backend

build_prod:
  stage: build
  tags:
  - part-pack
  rules:
  - if: '$CI_COMMIT_MESSAGE =~ /\[production\]/'
  script:
  - docker build -t "$IMAGE_NAME:$IMAGE_TAG" .

deploy_dev:
  stage: deploy
  rules:
  - if: '$CI_COMMIT_MESSAGE =~ /\[dev\]/' 
  tags:
  - part-pack-backend-dev
  needs:
  - build_dev
  script:
  - docker image inspect registry.part-pack.ir/part-pack/backend:development --format '{{.Id}}'
  - docker compose -f /deploy/docker-compose.yml up -d --no-deps --force-recreate backend
  - docker ps -a
  - docker inspect part-pack-dev-backend-1 --format '{{.Image}}'

deploy_prod:
  stage: deploy
  tags:
  - part-pack
  rules:
  - if: '$CI_COMMIT_MESSAGE =~ /\[production\]/'
  needs:
  - build_prod
  script:
  - 'chmod +x scripts/trigger-infra-deploy.sh'
  - './scripts/trigger-infra-deploy.sh'